language: python
dist: trusty
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" 
  allow_failures:
    - python "3.7-dev"
matrix:
  include:
    - addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-6', 'gzip']
      env: 
          - TRAVIS_GFORTRAN=gfortran-6
    - addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-7', 'gzip']
      env: 
          - TRAVIS_GFORTRAN=gfortran-7
    - addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-5', 'gzip']
      env: 
          - TRAVIS_GFORTRAN=gfortran-5
    - addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['gfortran-4.9', 'gzip']
      env: 
          - TRAVIS_GFORTRAN=gfortran-4.9
install: 
    - pip install -r requirements.txt
    - pip install -e .[dev]
    - python setup.py install
# command to run tests
script: 
    - coverage run --source=gfort2py setup.py test
sudo: required
after_success:
    coveralls
env:
  global
    - TRAVIS=1
